### ISSUE TITLE
[Multi-Language]

### ISSUE THREAD

**Issue by Amel7400** [202306-NEA-DZ-FEW/HopeHub#10]
**Task title**
Implement Multi-Language Functionality

**Task description**
Enhance the website to support multiple languages to cater to a broader audience. The multi-language functionality should include the ability to switch between languages, translate content, and provide a seamless user experience for users who prefer different languages. This task may involve integrating translation libraries, creating language-specific content, and ensuring a user-friendly language selector. Additionally, make sure the functionality works well across different devices and screen sizes.

**Subtasks**

- [ ] Fetch blogdata from firestore
- [ ] Translate that data using the google translation api

**Screenshots**
Put at least one screenshot here

**Link to the component on Figma**
Put the link here

**Comment by fketta** [comment]
Not implemented.
