### ISSUE TITLE
feature/login-Signup

### ISSUE THREAD

**Issue by Amel7400** [202306-NEA-DZ-FEW/HopeHub#25]
**Task title**
Firbase Authentication

**Task description**
Put the description here (Mandatory)

**Subtasks**
Put the subtasks here if any (optional)

**Screenshots**
Put at least one screenshot here

**Link to the component on Figma**
Put the link here

**Comment by GhaniBahri** [comment]
FireBase is configurated, just export `auth` from `firebas.js` and use it with Firebase functions in the login/signup forms
would be beneficial if you use context to detect user AuthChange and store his data
