### ISSUE TITLE
[Contact]

### ISSUE THREAD

**Issue by Amel7400** [202306-NEA-DZ-FEW/HopeHub#7]
**Task title**
Create Contact page

**Task description**
Develop and design the Contact page for our online therapy website. The Contact page should offer visitors an easy way to get in touch with us, including a contact form, phone number, email address, and any other relevant contact information. This task includes layout design, form integration, content creation, and ensuring mobile responsiveness.

**Subtasks**

- [x]  Form component

- [x]  snapshot test

- [x]  translatation to 3 languages

- [x] basic styling with tailwind css

**Screenshots**
![contact](https://github.com/202306-NEA-DZ-FEW/HopeHub/assets/138016246/d98e8c45-aad0-4636-8ad8-0eb6a0db5fff)

**Link to the component on Figma**
[Put the link here](https://www.figma.com/file/MhJAQ6EPFOUOp2CDYXgzlW/Hope-Hub?type=design&node-id=10673-306&mode=design&t=BhqKkcXx30zpE6ss-4)

**Comment by fketta** [comment]
Working on changing the styling for this page.
