### ISSUE TITLE
[Dark Mode:Re]

### ISSUE THREAD

**Issue by Amel7400** [202306-NEA-DZ-FEW/HopeHub#73]
**Task title**
enhancement and revision

**Task description**
Add dark mode to all webpages

**Subtasks**
- [x] Home Page 
- [x] Blogs Page
- [ ] ...
- [ ] Fix darkmode toggle

**Screenshots**
Put at least one screenshot here

**Link to the component on Figma**
Put the link here

**Comment by fketta** [comment]
@Zohir-kk If you can, for organization purposes, add all the pages that dark mode has been set up on please to the subtasks! Thank you in advance!

**Comment by Zohir-kk** [comment]
> @Zohir-kk If you can, for organization purposes, add all the pages that dark mode has been set up on please to the subtasks! Thank you in advance! 

That's my plan
