### ISSUE TITLE
[Requires Auth]

### ISSUE THREAD

**Issue by Amel7400** [202306-NEA-DZ-FEW/HopeHub#80]
**Task title**
Authentification requirement

**Task description**
Require authentification from users when they attemp to select an option that needs a user to be logged in.

**Subtasks**
Put the subtasks here if any (optional)

**Screenshots**
Put at least one screenshot here

**Link to the component on Figma**
Put the link here

**Comment by fketta** [comment]
Opening a new issue for this to not deal with merging develop conflicts.
